name: IGRM_Env_py310
channels:
  - conda-forge
  - defaultsdependencies:
  - python=3.10
  - reportlab
  - qrbill
  - svglib
  - pandas
  - notebook
  - jupyterthemes
  - python-dotenv
  - openpyxl
  - msal
