name: IGRM_Env_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - reportlab
  - svglib
  - pandas
  - notebook
  - jupyterthemes
  - python-dotenv
  - openpyxl
  - msal
  - pip
